[package]
name = "hal-sim"
version = "0.1.0"
edition = "2021"

[features]
default = ["nightly"]
nightly = []

[dependencies]
nb = "1"
embedded-hal = { version = "0.2", features = ["unproven"] }
embedded-graphics-core = "0.3"
embedded-svc = { version = "0.23", default-features = false, git = "https://github.com/esp-rs/embedded-svc", features = ["experimental", "nightly"] }
heapless = "0.7"
futures = "0.3"
postcard = "0.7"
serde = { version = "1", default-features = false }
embassy-futures = { version = "0.1", git = "https://github.com/ivmarkov/embassy" }
embassy-sync = { version = "0.1", git = "https://github.com/ivmarkov/embassy" }
edge-net = { version = "0.1", git = "https://github.com/ivmarkov/edge-net", features = ["nightly", "embassy-util", "embedded-svc"] }
#edge-net = { version = "0.1", path = "../edge-net", features = ["nightly", "embassy-util", "embedded-svc"] }
