[package]
name = "hal-sim"
version = "0.1.0"
edition = "2021"

[features]
default = ["nightly", "ws", "ui"]
nightly = []
sim = ["nb", "embedded-hal", "embedded-graphics-core"]
web = ["sim", "futures", "embassy-futures", "embassy-sync"]
ws = ["web", "edge-net"]
ui = ["edge-frame"]

[dependencies]
nb = { version = "1", optional = true }
embedded-hal = { version = "0.2", features = ["unproven"], optional = true }
embedded-graphics-core = { version = "0.3", optional = true }
embedded-svc = { version = "0.23", default-features = false, git = "https://github.com/esp-rs/embedded-svc", features = ["experimental", "nightly"], optional = true }
heapless = "0.7"
futures = { version = "0.3", optional = true }
postcard = "0.7"
serde = { version = "1", default-features = false }
embassy-futures = { version = "0.1", git = "https://github.com/ivmarkov/embassy", optional = true }
embassy-sync = { version = "0.1", git = "https://github.com/ivmarkov/embassy", optional = true }
edge-net = { version = "0.1", git = "https://github.com/ivmarkov/edge-net", features = ["nightly", "embassy-util", "embedded-svc"], optional = true }
edge-frame = { version = "0.3", git = "https://github.com/ivmarkov/edge-frame", optional = true }
