[package]
name = "hal-sim"
version = "0.1.0"
edition = "2021"

[features]
default = ["nightly", "ui", "web", "middleware-local"]
nightly = []
sim = ["nb", "embedded-hal", "embedded-graphics-core"]
web = ["sim", "futures", "embassy-futures", "embassy-sync", "channel-bridge"]
ws = ["web", "channel-bridge"]
ui = ["yew", "yewdux", "yewdux-middleware", "wasm-logger", "wasm-bindgen", "wasm-bindgen-futures", "web-sys", "itertools"]
middleware-ws = ["gloo-net", "postcard/alloc"]
middleware-local = ["embassy-sync"]

[dependencies]
serde = { version = "1", default-features = false }
heapless = { version = "0.7", features = ["serde"] }
log = "0.4"

# sim
nb = { version = "1", optional = true }
embedded-hal = { version = "0.2", features = ["unproven"], optional = true }
embedded-graphics-core = { version = "0.3", optional = true }

# web
futures = { version = "0.3", optional = true }
embassy-futures = { version = "0.1", optional = true }
embassy-sync = { version = "0.1", optional = true }
channel-bridge = { version = "0.1", git = "https://github.com/ivmarkov/channel-bridge", default-features = false, features = ["nightly", "embedded-svc", "notification"], optional = true }
gloo-net = { version = "0.2", optional = true }
postcard = { version = "1", optional = true }

# ws
embedded-svc = { version = "0.23", default-features = false, git = "https://github.com/esp-rs/embedded-svc", features = ["experimental", "nightly"], optional = true }

# ui
yew = { version = "0.19", default-features = false, optional = true }
yewdux = { version = "=0.8.1", default-features = false, optional = true }
yewdux-middleware = { version = "0.1", git = "https://github.com/ivmarkov/yewdux-middleware", optional = true }
wasm-logger = { version = "0.2", optional = true }
wasm-bindgen = { version = "0.2", optional = true }
wasm-bindgen-futures = { version = "0.4", optional = true }
web-sys = { version = "0.3", optional = true, features = ["console", "CanvasRenderingContext2d", "ImageData", "HtmlCanvasElement"] }
itertools = { version = "0.10", optional = true }
